// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFQSZL7V5DSGE9qfCFCOlAXfxgaWpggxs',
    appId: '1:716394320442:web:efe04253d282c7e4345b03',
    messagingSenderId: '716394320442',
    projectId: 'gym-tracker-83c77',
    authDomain: 'gym-tracker-83c77.firebaseapp.com',
    storageBucket: 'gym-tracker-83c77.firebasestorage.app',
    measurementId: 'G-KZM1EXWK24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBBegNfcUs90vgBde8wathk7QFPso3kZ0',
    appId: '1:716394320442:android:bca965d9675102d9345b03',
    messagingSenderId: '716394320442',
    projectId: 'gym-tracker-83c77',
    storageBucket: 'gym-tracker-83c77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOlDoFCuAvK14wMVbCC8sq_UUWmcqh5ks',
    appId: '1:716394320442:ios:ff49d43a39606d4a345b03',
    messagingSenderId: '716394320442',
    projectId: 'gym-tracker-83c77',
    storageBucket: 'gym-tracker-83c77.firebasestorage.app',
    iosBundleId: 'com.example.taskmanagerapp',
  );
}
